# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/stream8"
  config.vm.box_url = "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-Vagrant-8-20201217.0.x86_64.vagrant-virtualbox.box"
  config.ssh.insert_key = false
  config.vbguest.installer_options = {
      allow_kernel_upgrade: true, enablerepo: true
  }

  config.vm.provider :virtualbox do |v|
    v.name = "docker-centos-s8"
    v.memory = 4096
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
    v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end

  config.vm.hostname = "docker-centos-s8"
  config.vm.network :private_network, ip: "192.168.44.4"
  config.vm.network "forwarded_port", guest: 2376, host: 2376

  config.vm.synced_folder "/Users", "/Users"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :"docker-centos-s8" do |docker|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "../resources/playbook.yml"
    ansible.inventory_path = "inventory"
    ansible.become = true
  end

end
